[package]
name = "showobj"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
colored = "2.0"
crossterm = "0.27"
wgpu = "0.17"
pollster = "0.3"
winit = "0.28"
bytemuck = { version = "1.12", features = ["derive"] }